language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: required
dist: trusty

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer config --list --global
  - ./sandbox_setup.sh
  
script:
  - cd sandbox;export DISPLAY=:99.0;sh -e /etc/init.d/xvfb start;./vendor/laravel/dusk/bin/chromedriver-linux &;php artisan dusk:install;php artisan serve --env=dusk.local &;php artisan dusk;cd ..;
  - cd sandbox;php artisan adminlte:admin;./vendor/bin/phpunit --coverage-text --coverage-clover=../coverage.clover;cd ..;
  - vendor/bin/phpcs --standard=psr2 src/

after_script:
  - ./sandbox_destroy.sh
  - |
      if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi
